### PR TITLE
fix: Use readmeSummary instead of full readme to avoid context bloat

### LINKED ISSUE #422: Use Actor readme summary instead of full Actor readme
Actor readmes are typically huge and fill up context

Use the AI-generated summary (stored in Mongo) instead of the README.
Expose this summary via the public API and use it in the MCP server.

FYI @Jkuzz in kitchen we discussed that we can use the same summary that you’re using for Actor quality. 
I'm tagging you here to reconsider :)

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #422
- [x] Resolve code TODO
- [x] Release API client and use stable release instead of beta here

### CODE REVIEW

File: src/tools/build.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export async function getActorDefinition(
             const actorDefinitions = buildDetails?.actorDefinition as ActorDefinitionWithDesc;
             // We set actorDefinition ID to Actor ID
             actorDefinitions.id = actor.id;
-            actorDefinitions.readme = truncateActorReadme(actorDefinitions.readme || '', limit);
+            actorDefinitions.readme = actor.readmeSummary ?? truncateActorReadme(actorDefinitions.readme || '', limit);
```
Comment (jirispilka) [inline src/tools/build.ts]: @janbuchar we might need to use full Actor readme in `ActorSearchDetail` in `src/web/src/pages/ActorSearch/ActorSearchDetail.tsx`

I think we should add a new field, we might need to use the full readme at some point.
